### ISSUE TITLE
Multiple middle names get reversed

### ISSUE THREAD

**Issue by barwin** [chovy/humanparser#10]
P/R coming soon, I discovered this issue earlier when I was trying to parse a name that had multiple middle names.

So a name like `Tommy A B Lee` would come back with a `middleName: 'B A'` when it should have had `middleName: 'A B'`

p.s. Thanks for a very helpful module.

**Comment by chovy** [comment]
i commented on your PR. Just want to make sure the compound last names still work (see index.js).
Thanks for the submission.
