### ISSUE TITLE
Consider adding Typings for TypeScript

### ISSUE THREAD

**Issue by MichalPodeszwa** [chovy/humanparser#15]
Thank you for the library.
Would you be willing to add TypeScript typings? Or at least review them (I can add them).

http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html Here's a reference on what it is and how works.

If you want an example of how it is done, https://github.com/DefinitelyTyped/DefinitelyTyped/ is a good source of knowledge

**Comment by chovy** [comment]
I don't have any interest in TypeScript.
