### ISSUE TITLE
Does not parse suffixes when in the format "Hearst Jr., William Randolf"

### ISSUE THREAD

**Issue by racedale** [chovy/humanparser#17]
Returns "lastname": ""Hearst Jr."

This format of writing names is not in the tests, and unfortunately breaks the parsing ability.  This is the format of names for one of the databases I inherited recently.

I tried to split the last name based off of spaces, but of course that then breaks multiple word last names like "Van De Car"

**Comment by chovy** [comment]
Fixed with https://github.com/chovy/humanparser/commit/b88c08ef6a9a6032e2536539747821c1a5e8e892

published v1.2.0 on npm
