### ISSUE TITLE
Demo site needed

### ISSUE THREAD

**Issue by robertbaker** [chovy/humanparser#4]

**Comment by chovy** [comment]
What are you expecting to see in a demo site?

**Comment by robertbaker** [comment]
I want to test how well this parses names. Throw some names at it and see what it does.

Demos are useful :)

**Comment by chovy** [comment]
Would an example script help? I don't think its necessary to build a full blown web site just to show case what's done w/ a few lines of node.js

**Comment by robertbaker** [comment]
Just a simple input box that I can test the plugin without needing to
download and run the script with node (which is unclear)

On Sat, May 16, 2015 at 12:21 AM, Anthony Ettinger <notifications@github.com

**Comment by chovy** [comment]
Checkout tonicdev.com -- here's an example: https://tonicdev.com/sajin/56282fac4826d80d005e1ca4
