### ISSUE TITLE
Missing letter T in README.md

### ISSUE THREAD

**Issue by PogromistDev** [chovy/humanparser#41]
//produces the following output

{ 
    salu T ation: 'Mr.',
    firstName: 'William',
    suffix: 'III',
    lastName: 'Hearst',
    middleName: 'R.',
    fullName: 'Mr. William R. Hearst, III'
}

**Comment by chovy** [comment]
please submit a PR

**Comment by PogromistDev** [comment]
Ok, don't know why i need to PR if you can edit it on github.

**Comment by chovy** [comment]
fixed.
