### ISSUE TITLE
Returns `undefined` lastName

### ISSUE THREAD

**Issue by sajinshrestha** [chovy/humanparser#6]
If you pass just the first name, lastName is set to undefined. Should this return empty string instead of `undefined`? 

var name = human.parseName('John');
//  {firstName: "John", fullName: "John", lastName: undefined}

https://tonicdev.com/sajin/56282fac4826d80d005e1ca4

**Comment by chovy** [comment]
Is there some reason `undefined` is causing a problem? Its not really defined so...

I can make it an empty string, but I think its more logical that its undefined. Can you explain the problem you're having with it being undefined?

**Comment by sajinshrestha** [comment]
Working with one, required, input field for 'name'. I'm trying to extract 'firstName' and 'lastName'.  

If I'm reading your code correctly, 'humanparser' will always returns three properties - firstname, fullName, and lastName, regardless of what's passed. If you pass `''` empty string, on line 13 parts.length would equal `1` and skip the `if statement`.  //parts → [""]

Right now, `humanparser.parseName('')` would return `Object {firstName: "", fullName: "", lastName: undefined}`. 

I can check for undefined 'lastName' and set it to empty string. But it would be nice to get an empty string for lastName by default for consistency.

Thanks.

**Comment by sajinshrestha** [comment]
I can create a pull request, but I'm not sure if you want to return all the default properties or just the parsed data. 

```
{ 
    saluation: '',
    firstName: '',
    suffix: '',
    lastName: '',
    middleName: '',
    fullName: ''
}
```
Thanks again for looking into this.

**Comment by chovy** [comment]
Ok, I'll see if I can patch this tonight. Feel free to send a PR. It should be consistent with other attributes.

**Comment by chovy** [comment]
I haven't gotten around to this. Feel free to submit a PR -- I think the attributes should just be empty, as the other ones currently are if they are not found. Thanks.
